// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { loadEnvFile } from "node:process";
import { defineConfig } from "prisma/config";

loadEnvFile();

if (process.env["DATABASE_URL"] === undefined)
  throw new Error("DATABASE_URL not defined");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
